server:
  port: 9411
spring:
  application:
    name: zipkin-server
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url.defaultZone: http://localhost:8700/eureka/
info:
  app:
    name: zipkin-server
    description: Zipkin Server
    version: v1.0
endpoints:
  actuator:
    enabled: true
    sensitive: true
  health:
    enabled: true
    sensitive: true
  metrics:
    enabled: true
    id: metrics
    sensitive: true
management:
  security:
    enabled: false